config/routes.rb
Rails.application.routes.draw do
  root 'records#index'

  resources :records
  get '/search' => 'search#search', :as => 'search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :record
end

app/models/record.rb
class Record < ApplicationRecord
  has_many :notifications
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def flash_message(response)
    flash[:success] = { data: response[:success] } if response[:success]
    flash[:error] = { data: response[:error] } if response[:error]
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  def index
    @records = Record.last(5)
  end

  def show
    @record = Record.find(params[:id])
  end

  def create
    response = RecordCreatorService.call(params[:url])
    if response[:error].present?
      flash_message(response)
      redirect_to new_record_path
    else
      redirect_to record_url(response[:id])
    end
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  before_action :redirect_no_query, only: %w[search]

  def search
    @records = Record.where('defendant LIKE ?', "%#{query}%")

    redirect_no_records if @records.count.zero?
  end

  private

  def query
    params[:name]
  end

  def redirect_no_query
    redirect_no_records if query.empty?
  end

  def redirect_no_records
    flash_message({ error: I18n.t('not_found_records')})
    redirect_to records_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ content: 'width=device-width, initial-scale=1, shrink-to-fit=no', name: 'viewport'}
    %meta{content_container: 'text/html; charset=UTF-8', 'http-equiv': 'Content-Type'}
    %title PoderJudicial
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %nav.navbar.navbar-expand-lg.navbar-light.bg-light
      %a.navbar-brand{ href: '#'} PoderJudicial
      %button.navbar-toggler{'data-target': '#navbar', 'data-toggle': 'collapse', type: 'button'}
        %span.navbar-toggler-icon
      #navbar.collapse.navbar-collapse
        %ul.navbar-nav.mr-auto
          %li.nav-item
            = link_to t('create_record'), new_record_path, class: 'nav-link'
          %li.nav-item
            = link_to t('search_by_defendant'), records_path, class: 'nav-link'

    - flash.each do |_type, msg|
      .alert{ class: "alert-danger" }
        %span.ml-2
          = msg['data']

    = yield

app/views/records/_record.html.haml
.card.mt-3
  .card-body
    %h5.card-title= record.name
    %h6.card-subtitle.mb-2.text-muted= "#{Record.human_attribute_name('actor')}: #{record.actor}"
    %h6.card-subtitle.mb-2.text-muted= "#{Record.human_attribute_name('defendant')}: #{record.defendant}"
    %p.card-text= record.summary
    = link_to t('show_record'), record_url(record.id)

app/views/records/index.html.haml
.container
  .row.justify-content-center
    .col.col-6.pt-5
      = t('search_record_by_name')

      = form_tag search_path, method: 'get', class: 'pt-5' do
        .form-group
          = text_field_tag 'name', '', placeholder: 'Pedro Perafán ...', class: 'form-control'
        .form-group
          = submit_tag t('search'), class: 'btn btn-primary'

  .row.mt-5
    %h1= t('last_records')
    - @records.each do |record|
      = render 'records/record', record: record

app/views/records/new.html.haml
.container
  .row.justify-content-center
    .col.col-6.pt-5
      = "#{t('create_record')}."
      = t('enter_url_domain')

      = form_tag records_url, class: 'pt-5' do
        .form-group
          = text_field_tag 'url', '', placeholder: 'https://www.poderjudicialvirtual.com/...', class: 'form-control'
        .form-group
          = submit_tag t('create_record'), class: 'btn btn-primary'

app/views/records/show.html.haml
.container
  .row
    .card
      .card-body
        %h5.card-title= @record.name
        %h6.card-subtitle.mb-2.text-muted= "#{Record.human_attribute_name('actor')}: #{@record.actor}"
        %h6.card-subtitle.mb-2.text-muted= "#{Record.human_attribute_name('defendant')}: #{@record.defendant}"
        %h6.card-subtitle.mb-2.text-muted= "#{Record.human_attribute_name('court')}: #{@record.court}"
        %h6.card-subtitle.mb-2.text-muted= "#{Record.human_attribute_name('city')}: #{@record.city}"
        %h6.card-subtitle.mb-2.text-muted= "#{Record.human_attribute_name('code')}: #{@record.code}"
        %p.card-text= @record.summary

    %h4.mt-3 = t('notifications')

    - if @record.notifications.count.zero?
      = t('no_notifications')
    - else
      - @record.notifications.each do |notification|
        .card.mt-3
          .card-body
            %h6.card-subtitle.mb-2.text-muted= notification.date
            %p.card-text= notification.message

app/views/search/search.html.haml
.container
  .row
    - @records.each do |record|
      = render 'records/record', record: record